# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-devel
sudo: false
cache: packages
warnings_are_errors: true
github_packages:
  - assertthat
  - devtools
bioc_packages:
  - AnnotationHub
  - biomaRt
  - DESeq2
  - gage
  - gageData
  - pathview
before_install:
  - tlmgr install index
